name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: makeGenerator
      run: cd src && javac MazeGenerator.java
    - name: runGenerator
      run: cd src && java MazeGenerator 5 6 maze.dat
    - name: makeSolverDFS
      run: cd src && javac MazeSolverDFS.java
    - name: runSolverDFS
      run: cd src && java MazeSolverDFS maze.dat
